spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/team_task_manager
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
app:
  jwt:
    secret: "change-me-change-me-change-me-change-me"
